# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - cottonpromptapp-prod

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NEXT_PUBLIC_API_URL: https://cottonpromptapi-prod.azurewebsites.net
  NEXT_PUBLIC_IMAGE_UPLOAD_MAX_SIZE_IN_MB: 10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: move static folder
        run: mv .next/static .next/standalone/.next

      - name: move public folder
        run: mv public .next/standalone

      - name: Zip artifact for deployment
        run: (cd .next/standalone && zip -r ../../release.zip .)

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "cottonpromptapp-prod"
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D3C4E0C2B465440F85D9EB23905B3E88 }}
